FROM jenkins/jenkins:lts

# Switch to root to install packages
USER root

# Install necessary packages
RUN apt-get update && apt-get install -y apt-transport-https \
   ca-certificates curl gnupg2 \
   software-properties-common

# Add Docker's official GPG key
RUN curl -fsSL https://download.docker.com/linux/debian/gpg | apt-key add -

# Add Docker repository
RUN add-apt-repository \
   "deb [arch=amd64] https://download.docker.com/linux/debian \
   $(lsb_release -cs) stable"

# Install Docker CLI
RUN apt-get update && apt-get install -y docker-ce-cli

# Install Git
RUN apt-get install -y git

# Create the docker group and add the jenkins user to it
RUN groupadd docker 
RUN usermod -aG docker jenkins