version: '3'

services:
  flask-app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    environment:
      - GIT_USER_NAME=Dylan Chew
      - GIT_USER_EMAIL=2101110@sit.singaporetech.edu.sg

  nginx:
    build: .
    ports:
      - "80:80"
    depends_on:
      - flask-app
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf

  git-config:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - GIT_USER_NAME=Dylan Chew
      - GIT_USER_EMAIL=2101110@sit.singaporetech.edu.sg

  jenkins:
    build:
      context: .
      dockerfile: Dockerfile-jenkins
    ports:
      - "8080:8080"
    volumes:
      - ./jenkins-data:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - frontend

networks:
  frontend:

volumes:
  jenkins-data:
